<?php

return [
    [
        'restaurant_id' => 1,
        'slug' => 'margherita',
        'name' => 'Margherita',
        'price' => 8.50,
        'description' => 'Una deliziosa pizza con pomodoro, mozzarella e basilico.',
        'availability' => 1,
        'image' => 'dishes/pizzeria-italia/margerita.jpeg',
    ],
    [
        'restaurant_id' => 1,
        'slug' => 'quattro-formaggi',
        'name' => 'Quattro Formaggi',
        'price' => 10.50,
        'description' => 'Pizza con una selezione di quattro formaggi: mozzarella, gorgonzola, pecorino e parmigiano.',
        'availability' => 1,
        'image' => 'dishes/pizzeria-italia/4-formaggi.jpeg',
    ],
    [
        'restaurant_id' => 1,
        'slug' => 'diavola',
        'name' => 'Diavola',
        'price' => 9.50,
        'description' => 'Con salame piccante, peperoncino e mozzarella.',
        'availability' => 1,
        'image' => 'dishes/pizzeria-italia/diavola.jpeg',
    ],
    [
        'restaurant_id' => 1,
        'slug' => 'capricciosa',
        'name' => 'Capricciosa',
        'price' => 10.00,
        'description' => 'Con prosciutto cotto, funghi, carciofi, olive e mozzarella.',
        'availability' => 1,
        'image' => 'dishes/pizzeria-italia/capricciosa.jpeg',
    ],
    [
        'restaurant_id' => 1,
        'slug' => 'vegetariana',
        'name' => 'Vegetariana',
        'price' => 8.00,
        'description' => 'Con pomodoro, mozzarella, peperoni, zucchine, melanzane e cipolla.',
        'availability' => 1,
        'image' => 'dishes/pizzeria-italia/vegetaiana.jpg',
    ],
    [
        'restaurant_id' => 1,
        'slug' => 'birra',
        'name' => 'Birra',
        'price' => 4.00,
        'description' => 'Una birra fresca per accompagnare la tua pizza.',
        'availability' => 1,
        'image' => 'dishes/pizzeria-italia/birra.jpg',
    ],
    [
        'restaurant_id' => 1,
        'slug' => 'coca-cola',
        'name' => 'Coca-Cola',
        'price' => 2.50,
        'description' => 'Bevanda gassata e rinfrescante.',
        'availability' => 1,
        'image' => 'dishes/pizzeria-italia/coca-cola.jpg',
    ],
    [
        'restaurant_id' => 1,
        'slug' => 'acqua',
        'name' => 'Acqua',
        'price' => 1.00,
        'description' => 'Acqua naturale.',
        'availability' => 1,
        'image' => 'dishes/pizzeria-italia/acqua.jpg',
    ],
    [
        'restaurant_id' => 2,
        'slug' => 'biryani-di-verdure',
        'name' => 'Biryani di Verdure',
        'price' => '10.99',
        'description' => 'Un delizioso biryani di verdure, ricco di sapori speziati.',
        'availability' => 1,
        'image' => 'dishes/curry-house/biryani-di-verdure.jpg',
    ],
    [
        'restaurant_id' => 2,
        'slug' => 'chole-bhature',
        'name' => 'Chole Bhature',
        'price' => '9.99',
        'description' => 'Un classico piatto indiano con ceci e pane fritto.',
        'availability' => 1,
        'image' => 'dishes/curry-house/chole-bhature.jpg',
    ],
    [
        'restaurant_id' => 2,
        'slug' => 'meetha-paan',
        'name' => 'Meetha Paan',
        'price' => '4.99',
        'description' => 'Un dolce tradizionale indiano fatto con foglie di betel.',
        'availability' => 0,
        'image' => 'dishes/curry-house/meetha-paan.jpg',
    ],
    [
        'restaurant_id' => 2,
        'slug' => 'pollo-al-curry',
        'name' => 'Pollo al Curry',
        'price' => '12.99',
        'description' => 'Un piatto ricco e speziato con pollo marinato nel curry.',
        'availability' => 1,
        'image' => 'dishes/curry-house/pollo-al-curry.jpg',
    ],
    [
        'restaurant_id' => 2,
        'slug' => 'pollo-tandoori',
        'name' => 'Pollo Tandoori',
        'price' => '13.99',
        'description' => 'Pollo marinato in spezie e cotto in un forno tandoor.',
        'availability' => 1,
        'image' => 'dishes/curry-house/pollo-tandoori.jpeg',
    ],
    [
        'restaurant_id' => 2,
        'slug' => 'samosa',
        'name' => 'Samosa',
        'price' => '5.99',
        'description' => 'Un antipasto croccante ripieno di patate e piselli speziati.',
        'availability' => 1,
        'image' => 'dishes/curry-house/samosa.jpg',
    ],
    [
        'restaurant_id' => 3,
        'slug' => 'hosomaki-fritti',
        'name' => 'Hosomaki Fritti',
        'price' => '6.99',
        'description' => 'Deliziosi sushi fritti.',
        'availability' => 1,
        'image' => 'dishes/sushi-sake/hosomaki-fritti.jpg',
    ],
    [
        'restaurant_id' => 3,
        'slug' => 'nighiri-misti',
        'name' => 'Nighiri Misti',
        'price' => '12.99',
        'description' => 'Un assortimento di sushi.',
        'availability' => 1,
        'image' => 'dishes/sushi-sake/nighiri.jpg',
    ],
    [
        'restaurant_id' => 3,
        'slug' => 'nighiri-salmone',
        'name' => 'Nighiri Salmone',
        'price' => '11.99',
        'description' => 'Sushi con un topping di salmone fresco.',
        'availability' => 1,
        'image' => 'dishes/sushi-sake/nighiri-salmone.jpg',
    ],
    [
        'restaurant_id' => 3,
        'slug' => 'nighiri-tonno',
        'name' => 'Nighiri Tonno',
        'price' => '11.99',
        'description' => 'Sushi con un topping di tonno fresco.',
        'availability' => 1,
        'image' => 'dishes/sushi-sake/nighiri-tonno.png',
    ],
    [
        'restaurant_id' => 3,
        'slug' => 'roll-di-salmone',
        'name' => 'Hosomaki di Salmone',
        'price' => '13.99',
        'description' => 'Sushi ripieno di salmone.',
        'availability' => 0,
        'image' => 'dishes/sushi-sake/hosomaki.jpg',
    ],
    [
        'restaurant_id' => 4,
        'slug' => 'burrito',
        'name' => 'Burrito',
        'price' => '8.99',
        'description' => 'Un piatto sostanzioso con riso, fagioli e carne avvolti in una tortilla.',
        'availability' => 1,
        'image' => 'dishes/taco-express/burrito.jpg',
    ],
    [
        'restaurant_id' => 4,
        'slug' => 'tacos',
        'name' => 'Tacos',
        'price' => '7.99',
        'description' => 'Tortillas croccanti riempite con carne, formaggio e salsa.',
        'availability' => 1,
        'image' => 'dishes/taco-express/tacos.jpg',
    ],
    [
        'restaurant_id' => 4,
        'slug' => 'enchiladas',
        'name' => 'Enchiladas',
        'price' => '9.99',
        'description' => 'Tortillas ripiene di carne e ricoperte di salsa piccante.',
        'availability' => 1,
        'image' => 'dishes/taco-express/enchiladas.jpg',
    ],
    [
        'restaurant_id' => 4,
        'slug' => 'quesadillas',
        'name' => 'Quesadillas',
        'price' => '8.99',
        'description' => 'Tortillas ripiene di formaggio e grigliate alla perfezione.',
        'availability' => 0,
        'image' => 'dishes/taco-express/quesadillas.jpg',
    ],
    [
        'restaurant_id' => 5,
        'slug' => 'anatra-alla-pechinese',
        'name' => 'Anatra alla Pechinese',
        'price' => '15.99',
        'description' => 'Un piatto tradizionale cinese con anatra arrosto.',
        'availability' => 1,
        'image' => 'dishes/dim-sum/anatra-alla-pechinese.jpg',
    ],
    [
        'restaurant_id' => 5,
        'slug' => 'involtini-primavera',
        'name' => 'Involtini Primavera',
        'price' => '6.99',
        'description' => 'Un antipasto croccante con verdure e carne.',
        'availability' => 1,
        'image' => 'dishes/dim-sum/involtini-primavera.jpg',
    ],
    [
        'restaurant_id' => 5,
        'slug' => 'involtini-di-carne',
        'name' => 'Involtini di Carne',
        'price' => '7.99',
        'description' => 'Un piatto delizioso con carne avvolta e cotta a vapore.',
        'availability' => 0,
        'image' => 'dishes/dim-sum/involtini-di-carne.jpg',
    ],
    [
        'restaurant_id' => 5,
        'slug' => 'ravioli-di-gamberi',
        'name' => 'Ravioli di Gamberi',
        'price' => '8.99',
        'description' => 'Un piatto di pasta ripiena di gamberi.',
        'availability' => 1,
        'image' => 'dishes/dim-sum/ravioli-di-gamberi.jpg',
    ],
    [
        'restaurant_id' => 5,
        'slug' => 'spaghetti-di-soia-con-verdure',
        'name' => 'Spaghetti di Soia con Verdure',
        'price' => '9.99',
        'description' => 'Un piatto vegetariano con spaghetti di soia e verdure fresche.',
        'availability' => 1,
        'image' => 'dishes/dim-sum/spaghetti-di-soia-con-verdure.jpg',
    ],
    [
        'restaurant_id' => 5,
        'slug' => 'zampe-di-rana-fritta',
        'name' => 'Zampe di Rana Fritta',
        'price' => '14.99',
        'description' => 'Un piatto audace con zampe di rana fritte croccanti.',
        'availability' => 1,
        'image' => 'dishes/dim-sum/zampe-di-rana-fritta.jpg',
    ],
    [
        'restaurant_id' => 6,
        'slug' => 'spaghetti-alla-amatriciana',
        'name' => 'Spaghetti alla Amatriciana',
        'price' => '10.99',
        'description' => 'Pasta con salsa di pomodoro, guanciale e pecorino.',
        'availability' => 1,
        'image' => 'dishes/essenza-del-gusto/amatriciana.jpg',
    ],
    [
        'restaurant_id' => 6,
        'slug' => 'spaghetti-alla-carbonara',
        'name' => 'Spaghetti alla Carbonara',
        'price' => '11.99',
        'description' => 'Pasta con uova, guanciale, pecorino e pepe.',
        'availability' => 1,
        'image' => 'dishes/essenza-del-gusto/carbonara.jpg',
    ],
    [
        'restaurant_id' => 6,
        'slug' => 'fettuccine-alla-bolognese',
        'name' => 'Fettuccine alla Bolognese',
        'price' => '12.99',
        'description' => 'Pasta con ragù di carne.',
        'availability' => 1,
        'image' => 'dishes/essenza-del-gusto/bolognese.jpg',
    ],
    [
        'restaurant_id' => 6,
        'slug' => 'lasagna',
        'name' => 'Lasagna',
        'price' => '13.99',
        'description' => 'Pasta al forno con ragù, besciamella e formaggio.',
        'availability' => 1,
        'image' => 'dishes/essenza-del-gusto/lasagna.jpg',
    ],
    [
        'restaurant_id' => 6,
        'slug' => 'linguine-alle-vongole',
        'name' => 'Linguine alle Vongole',
        'price' => '14.99',
        'description' => 'Pasta con vongole, aglio e prezzemolo.',
        'availability' => 0,
        'image' => 'dishes/essenza-del-gusto/vongole.jpg',
    ],
    [
        'restaurant_id' => 6,
        'slug' => 'risotto-ai-funghi',
        'name' => 'Risotto ai Funghi',
        'price' => '11.99',
        'description' => 'Risotto cremoso con funghi porcini.',
        'availability' => 1,
        'image' => 'dishes/essenza-del-gusto/risotto.jpg',
    ],
    [
        'restaurant_id' => 6,
        'slug' => 'tiramisu',
        'name' => 'Tiramisù',
        'price' => '6.99',
        'description' => 'Dolce al cucchiaio con savoiardi, caffè e mascarpone.',
        'availability' => 1,
        'image' => 'dishes/essenza-del-gusto/tiramisu.jpg',
    ],
    [
        'restaurant_id' => 7,
        'slug' => 'crema-di-lenticchie-rosse',
        'name' => 'Crema di Lenticchie Rosse',
        'price' => '7.99',
        'description' => 'Una crema liscia e nutriente fatta con lenticchie rosse.',
        'availability' => 1,
        'image' => 'dishes/veggy/crema.jpg',
    ],
    [
        'restaurant_id' => 7,
        'slug' => 'polpette-di-zucca-e-ceci',
        'name' => 'Polpette di Zucca e Ceci',
        'price' => '8.99',
        'description' => 'Polpette saporite fatte con zucca e ceci.',
        'availability' => 1,
        'image' => 'dishes/veggy/polpette.jpg',
    ],
    [
        'restaurant_id' => 7,
        'slug' => 'stufato-di-ceci-in-umido-con-verdure',
        'name' => 'Stufato di Ceci in Umido con Verdure',
        'price' => '9.99',
        'description' => 'Un ricco stufato con ceci e verdure fresche.',
        'availability' => 0,
        'image' => 'dishes/veggy/stufato.jpg',
    ],
    [
        'restaurant_id' => 7,
        'slug' => 'insalata-di-quinoa',
        'name' => 'Insalata di Quinoa',
        'price' => '8.99',
        'description' => 'Insalata fresca e nutriente con quinoa, pomodori e cetrioli.',
        'availability' => 1,
        'image' => 'dishes/veggy/insalata.jpg',
    ],
    [
        'restaurant_id' => 7,
        'slug' => 'zuppa-di-verdure',
        'name' => 'Zuppa di Verdure',
        'price' => '7.99',
        'description' => 'Zuppa calda e confortante con una varietà di verdure.',
        'availability' => 1,
        'image' => 'dishes/veggy/zuppa.jpg',
    ],
    [
        'restaurant_id' => 8,
        'slug' => 'delizia-di-manzo',
        'name' => 'Delizia di Manzo',
        'price' => '8.99',
        'description' => 'Un classico hamburgher con carne di manzo, lattuga, pomodoro e salsa.',
        'availability' => 1,
        'image' => 'dishes/burger-palace/manzo.jpg',
    ],
    [
        'restaurant_id' => 8,
        'slug' => 'pollo-principe',
        'name' => 'Pollo Principe',
        'price' => '9.99',
        'description' => 'Hamburgher con petto di pollo grigliato, lattuga e maionese.',
        'availability' => 1,
        'image' => 'dishes/burger-palace/pollo.jpg',
    ],
    [
        'restaurant_id' => 8,
        'slug' => 'sogno-di-uovo',
        'name' => 'Sogno di Uovo',
        'price' => '10.99',
        'description' => 'Hamburgher con carne di manzo, uovo fritto, bacon e formaggio.',
        'availability' => 1,
        'image' => 'dishes/burger-palace/uovo.jpg',
    ],
    [
        'restaurant_id' => 8,
        'slug' => 'cipolla-rossa-regale',
        'name' => 'Cipolla Rossa Regale',
        'price' => '9.99',
        'description' => 'Hamburgher con carne di manzo, cipolla rossa, pomodoro e salsa BBQ.',
        'availability' => 1,
        'image' => 'dishes/burger-palace/cipolla.jpg',
    ],
    [
        'restaurant_id' => 8,
        'slug' => 'menu-festa',
        'name' => 'Menu Festa',
        'price' => '12.99',
        'description' => 'Un menu completo con hamburgher, patatine fritte e Coca Cola.',
        'availability' => 1,
        'image' => 'dishes/burger-palace/festa.jpg',
    ],
    [
        'restaurant_id' => 8,
        'slug' => 'menu-leggero',
        'name' => 'Menu Leggero',
        'price' => '11.99',
        'description' => 'Un menu leggero con hamburgher, insalata mista e acqua.',
        'availability' => 1,
        'image' => 'dishes/burger-palace/leggero.jpg',
    ],
    [
        'restaurant_id' => 8,
        'slug' => 'patatine-dorate',
        'name' => 'Patatine Dorate',
        'price' => '3.99',
        'description' => 'Porzione di patatine fritte croccanti.',
        'availability' => 0,
        'image' => 'dishes/burger-palace/patatine.jpg',
    ],
    [
        'restaurant_id' => 8,
        'slug' => 'coca-cola',
        'name' => 'Coca-Cola',
        'price' => 2.50,
        'description' => 'Bevanda gassata e rinfrescante.',
        'availability' => 1,
        'image' => 'dishes/burger-palace/coca-cola.jpg',
    ],
    [
        'restaurant_id' => 8,
        'slug' => 'acqua',
        'name' => 'Acqua',
        'price' => 1.00,
        'description' => 'Acqua naturale.',
        'availability' => 1,
        'image' => 'dishes/burger-palace/acqua.jpg',
    ],
    [
        'restaurant_id' => 9,
        'slug' => 'sunny-salmon',
        'name' => 'Sunny Salmon',
        'price' => '12.99',
        'description' => 'Fresca e delicata. Con Salmone Norvegese, Avocado Hass ed edamame.',
        'availability' => 1,
        'image' => 'dishes/poke-house/salmone.jpg',
    ],
    [
        'restaurant_id' => 9,
        'slug' => 'spicy-tuna',
        'name' => 'Spicy Tuna',
        'price' => '11.99',
        'description' => 'Dal gusto intenso e piccante. Con Tonno, Goma Wakame, Jalapeño e Spicy Peanuts.',
        'availability' => 1,
        'image' => 'dishes/poke-house/tonno.jpg',
    ],
    [
        'restaurant_id' => 9,
        'slug' => 'roast-beef',
        'name' => 'Roast Beef',
        'price' => '13.99',
        'description' => 'Gustosa e ricercata. Con tenero Roast Beef all’inglese, Feta, Avocado Hass e Mandorle croccanti.',
        'availability' => 1,
        'image' => 'dishes/poke-house/roast-beef.jpg',
    ],
    [
        'restaurant_id' => 9,
        'slug' => 'chicken',
        'name' => 'Chicken',
        'price' => '13.99',
        'description' => 'Semplice e saporita. Con Pollo cotto a bassa temperatura mixato con salsa Teriyaki e Zenzero.',
        'availability' => 0,
        'image' => 'dishes/poke-house/pollo.jpg',
    ],
    [
        'restaurant_id' => 9,
        'slug' => 'super-protein',
        'name' => 'Super Protein',
        'price' => '14.99',
        'description' => 'Bilanciata e proteica. Con Pollo Teriyaki, Edamame, Scaglie di Grana Padano e Avocado Hass.',
        'availability' => 1,
        'image' => 'dishes/poke-house/proteica.jpg',
    ],
    [
        'restaurant_id' => 10,
        'slug' => 'onighiri',
        'name' => 'Onighiri',
        'price' => '3.99',
        'description' => 'Palline di riso giapponesi ripiene e avvolte in un foglio di alga nori.',
        'availability' => 1,
        'image' => 'dishes/nippon/onighiri.jpeg',
    ],
    [
        'restaurant_id' => 10,
        'slug' => 'ramen',
        'name' => 'Ramen',
        'price' => '12.99',
        'description' => 'Zuppa di noodle giapponese con brodo di carne o pesce, salsa di soia o miso e guarnita con maiale affettato, alghe e cipollotti.',
        'availability' => 1,
        'image' => 'dishes/nippon/ramen.jpeg',
    ],
    [
        'restaurant_id' => 10,
        'slug' => 'gyoza',
        'name' => 'Gyoza',
        'price' => '6.99',
        'description' => 'Ravioli giapponesi ripieni di carne o verdure e cotti al vapore.',
        'availability' => 0,
        'image' => 'dishes/nippon/gyoza.jpg',
    ],
    [
        'restaurant_id' => 10,
        'slug' => 'sashimi',
        'name' => 'Sashimi',
        'price' => '14.99',
        'description' => 'Pesce crudo affettato sottilmente e servito senza riso.',
        'availability' => 1,
        'image' => 'dishes/nippon/sashimi.jpg',
    ],
    [
        'restaurant_id' => 10,
        'slug' => 'gamberi-in-tempura',
        'name' => 'Gamberi in Tempura',
        'price' => '13.99',
        'description' => 'Gamberi fritti in un impasto leggero e croccante.',
        'availability' => 0,
        'image' => 'dishes/nippon/tempura.jpg',
    ],
    [
        'restaurant_id' => 11,
        'slug' => 'delizia-miso',
        'name' => 'Delizia Miso',
        'price' => '12.99',
        'description' => 'Ramen con brodo di miso, maiale, uovo e verdure.',
        'availability' => 1,
        'image' => 'dishes/ramen-house/miso.jpg',
    ],
    [
        'restaurant_id' => 11,
        'slug' => 'soia-sorpresa',
        'name' => 'Soia Sorpresa',
        'price' => '11.99',
        'description' => 'Ramen con brodo di soia, pollo, uovo e verdure.',
        'availability' => 1,
        'image' => 'dishes/ramen-house/soia.jpg',
    ],
    [
        'restaurant_id' => 11,
        'slug' => 'verde',
        'name' => 'Verde',
        'price' => '10.99',
        'description' => 'Ramen con brodo vegetale, tofu, uovo e verdure.',
        'availability' => 1,
        'image' => 'dishes/ramen-house/vegetariano.jpg',
    ],
    [
        'restaurant_id' => 11,
        'slug' => 'edamame-elegante',
        'name' => 'Edamame Elegante',
        'price' => '4.99',
        'description' => 'Fagioli di soia verdi bolliti in baccello e serviti con sale.',
        'availability' => 1,
        'image' => 'dishes/ramen-house/edamame.jpg',
    ],
    [
        'restaurant_id' => 12,
        'slug' => 'panino-kebab',
        'name' => 'Panino Kebab',
        'price' => '6.99',
        'description' => 'Panino farcito con carne di kebab, insalata e salsa.',
        'availability' => 1,
        'image' => 'dishes/suleman/panino.jpg',
    ],
    [
        'restaurant_id' => 12,
        'slug' => 'piadina-kebab',
        'name' => 'Piadina Kebab',
        'price' => '7.99',
        'description' => 'Piadina ripiena con carne di kebab, insalata e salsa.',
        'availability' => 1,
        'image' => 'dishes/suleman/piadina.jpg',
    ],
    [
        'restaurant_id' => 12,
        'slug' => 'falafel',
        'name' => 'Falafel',
        'price' => '6.99',
        'description' => 'Polpette di ceci fritte servite con salsa yogurt.',
        'availability' => 0,
        'image' => 'dishes/suleman/falafel.jpg',
    ],
    [
        'restaurant_id' => 12,
        'slug' => 'birra',
        'name' => 'Birra',
        'price' => 3.50,
        'description' => 'Una birra fresca per accompagnare la tua pizza.',
        'availability' => 1,
        'image' => 'dishes/suleman/birra.jpg',
    ],
    [
        'restaurant_id' => 12,
        'slug' => 'coca-cola',
        'name' => 'Coca-Cola',
        'price' => 2.00,
        'description' => 'Bevanda gassata e rinfrescante.',
        'availability' => 1,
        'image' => 'dishes/suleman/coca-cola.jpg',
    ],
    [
        'restaurant_id' => 12,
        'slug' => 'acqua',
        'name' => 'Acqua',
        'price' => 1.00,
        'description' => 'Acqua naturale.',
        'availability' => 1,
        'image' => 'dishes/suleman/acqua.jpg',
    ],
    [
        'restaurant_id' => 13,
        'slug' => 'entrectote',
        'name' => 'Entrectote',
        'price' => '15.99',
        'description' => 'Bistecca di manzo alla griglia servita con salsa e patate.',
        'availability' => 1,
        'image' => 'dishes/bbq-heaven/entrectote.jpg',
    ],
    [
        'restaurant_id' => 13,
        'slug' => 'pollo',
        'name' => 'Pollo',
        'price' => '10.99',
        'description' => 'Petto di pollo alla griglia marinato con spezie e erbe.',
        'availability' => 1,
        'image' => 'dishes/bbq-heaven/pollo.jpg',
    ],
    [
        'restaurant_id' => 13,
        'slug' => 'ribs',
        'name' => 'Ribs',
        'price' => '14.99',
        'description' => 'Costolette di maiale alla griglia con salsa BBQ.',
        'availability' => 1,
        'image' => 'dishes/bbq-heaven/ribs.jpg',
    ],
    [
        'restaurant_id' => 13,
        'slug' => 'tagliata-di-manzo',
        'name' => 'Tagliata di Manzo',
        'price' => '16.99',
        'description' => 'Fette di manzo alla griglia servite con rucola e pomodorini.',
        'availability' => 0,
        'image' => 'dishes/bbq-heaven/manzo.jpg',
    ],
    [
        'restaurant_id' => 13,
        'slug' => 'grigliata-mista-di-vitello',
        'name' => 'Grigliata Mista di Vitello',
        'price' => '18.99',
        'description' => 'Un assortimento di carni di vitello alla griglia.',
        'availability' => 1,
        'image' => 'dishes/bbq-heaven/vitello.jpg',
    ],
    [
        'restaurant_id' => 14,
        'slug' => 'delizia-al-cioccolato',
        'name' => 'Delizia al Cioccolato',
        'price' => '3.00',
        'description' => 'Gelato al cioccolato cremoso e ricco.',
        'availability' => 1,
        'image' => 'dishes/gelateria-delizia/cioccolato.jpg',
    ],
    [
        'restaurant_id' => 14,
        'slug' => 'vaniglia-velata',
        'name' => 'Vaniglia Velata',
        'price' => '3.50',
        'description' => 'Gelato alla vaniglia dolce e liscio.',
        'availability' => 1,
        'image' => 'dishes/gelateria-delizia/barattolo.jpg',
    ],
    [
        'restaurant_id' => 14,
        'slug' => 'brioches-di-gelato-fragola-e-stracciatella',
        'name' => 'Brioches di Gelato Fragola e Stracciatella',
        'price' => '4.99',
        'description' => 'Brioches ripiene di gelato alla fragola e stracciatella.',
        'availability' => 1,
        'image' => 'dishes/gelateria-delizia/brioches.jpg',
    ],
    [
        'restaurant_id' => 14,
        'slug' => 'cestino-di-frutta',
        'name' => 'Cestino di Frutta',
        'price' => '7.99',
        'description' => 'Cialda a forma di cestino contenente gelato alla frutta e mirtilli.',
        'availability' => 0,
        'image' => 'dishes/gelateria-delizia/frutta.jpg',
    ],
    [
        'restaurant_id' => 15,
        'slug' => 'tiramisu',
        'name' => 'Tiramisù',
        'price' => '4.99',
        'description' => 'Dolce al cucchiaio con savoiardi, caffè e mascarpone.',
        'availability' => 1,
        'image' => 'dishes/pasticceria-fantasia/tiramisu.jpg',
    ],
    [
        'restaurant_id' => 15,
        'slug' => 'cannoli',
        'name' => 'Cannoli',
        'price' => '5.99',
        'description' => 'Dolci siciliani con guscio croccante e ripieno di ricotta.',
        'availability' => 1,
        'image' => 'dishes/pasticceria-fantasia/cannoli.jpg',
    ],
    [
        'restaurant_id' => 15,
        'slug' => 'sfogliatella',
        'name' => 'Sfogliatella',
        'price' => '3.99',
        'description' => 'Dolce napoletano con pasta sfoglia e ripieno di ricotta.',
        'availability' => 1,
        'image' => 'dishes/pasticceria-fantasia/sfogliatella.jpg',
    ],
    [
        'restaurant_id' => 15,
        'slug' => 'panna-cotta',
        'name' => 'Panna Cotta',
        'price' => '4.99',
        'description' => 'Dolce al cucchiaio con panna cotta e salsa di frutta.',
        'availability' => 0,
        'image' => 'dishes/pasticceria-fantasia/panna-cotta.jpg',
    ],
    [
        'restaurant_id' => 15,
        'slug' => 'torta-di-mele',
        'name' => 'Torta di Mele',
        'price' => '5.99',
        'description' => 'Torta soffice con mele fresche e cannella.',
        'availability' => 1,
        'image' => 'dishes/pasticceria-fantasia/mele.jpg',
    ],
    [
        'restaurant_id' => 16,
        'slug' => 'espresso',
        'name' => 'Espresso',
        'price' => '1.50',
        'description' => 'Un classico caffè espresso italiano.',
        'availability' => 1,
        'image' => 'dishes/caffetteria-italia/espresso.jpg',
    ],
    [
        'restaurant_id' => 16,
        'slug' => 'cappuccino',
        'name' => 'Cappuccino',
        'price' => '2.50',
        'description' => 'Caffè con latte schiumato e cacao in polvere.',
        'availability' => 1,
        'image' => 'dishes/caffetteria-italia/cappuccino.jpg',
    ],
    [
        'restaurant_id' => 16,
        'slug' => 'cornetto',
        'name' => 'Cornetto',
        'price' => '1.00',
        'description' => 'Cornetto dolce, ripieno di crema pasticcera, di laboratorio.',
        'availability' => 1,
        'image' => 'dishes/caffetteria-italia/cornetto.jpg',
    ],
    [
        'restaurant_id' => 16,
        'slug' => 'ciambella',
        'name' => 'Ciambella',
        'price' => '3.50',
        'description' => 'Dolce soffice glassato al cioccolato.',
        'availability' => 0,
        'image' => 'dishes/caffetteria-italia/ciambella.png',
    ],
    [
        'restaurant_id' => 16,
        'slug' => 'panino-prosciutto',
        'name' => 'Panino Prosciutto',
        'price' => '3.00',
        'description' => 'Panino fresco farcito con prosciutto.',
        'availability' => 1,
        'image' => 'dishes/caffetteria-italia/panino-prosciutto.jpg',
    ],
];
