<?php
return [
    [
        'user_id' => 1,
        'name' => 'Pizzeria Italia',
        'slug' => 'pizzeria-italia',
        'address' => 'Via Nazionale, 12, Roma',
        'phone' => '+39 301 879 2346',
        'vat' => '11123456789',
        'description' => 'Pizza tradizionale italiana e altri piatti italiani.',
        'image' => 'restaurants/pizzeria-italia.jpg',
        'types' => ['Italiano', 'Pizzeria', 'Vegetariano'],
    ],
    [
        'user_id' => 2,
        'name' => 'Curry House',
        'slug' => 'curry-house',
        'address' => 'Piazza San Pietro, 5, Roma',
        'phone' => '+39 302 465 7389',
        'vat' => '12765432109',
        'description' => 'Cibi indiani speziati e curry aromatici.',
        'image' => 'restaurants/curry-house.jpeg',
        'types' => ['Indiano'],
    ],
    [
        'user_id' => 3,
        'name' => 'Sushi Sake',
        'slug' => 'sushi-sake',
        'address' => 'Piazza di Spagna, 2, Roma',
        'phone' => '+39 303 982 1467',
        'vat' => '13876543210',
        'description' => 'Sushi fresco e sashimi prelibati.',
        'image' => 'restaurants/Sake-Sushi-Logo.png',
        'types' => ['Giapponese', 'Sushi'],
    ],
    [
        'user_id' => 4,
        'name' => 'Taco Express',
        'slug' => 'taco-express',
        'address' => 'Piazza Navona, 3, Roma',
        'phone' => '+39 304 675 2398',
        'vat' => '14567890123',
        'description' => 'Tacos autentici e burritos deliziosi.',
        'image' => 'restaurants/taco-express.jpeg',
        'types' => ['Messicano'],
    ],
    [
        'user_id' => 5,
        'name' => 'Dim Sum Delight',
        'slug' => 'dim-sum-delight',
        'address' => 'Piazza del Popolo, 7, Roma',
        'phone' => '+39 305 789 3124',
        'vat' => '15012345678',
        'description' => 'Dim sum tradizionale e autentico.',
        'image' => 'restaurants/dim-sum.jpeg',
        'types' => ['Cinese', 'Vegetariano'],
    ],
    [
        'user_id' => 6,
        'name' => 'L’Essenza del Gusto',
        'slug' => 'l-essenza-del-gusto',
        'address' => 'Via Condotti, 30, Roma',
        'phone' => '+39 306 234 8976',
        'vat' => '16543210987',
        'description' => 'Cucina tipica italiana e servizio impeccabile.',
        'image' => 'restaurants/ristoranti-eleganti.jpeg',
        'types' => ['Italiano'],
    ],
    [
        'user_id' => 7,
        'name' => 'Veggy Deligth',
        'slug' => 'veggy-deligth',
        'address' => 'Piazza di Spagna, 20, Roma',
        'phone' => '+39 307 568 9123',
        'vat' => '17321098765',
        'description' => 'Pane fresco e dolci appena sfornati.',
        'image' => 'restaurants/veggy.png',
        'types' => ['Vegano', 'Vegetariano'],
    ],
    [
        'user_id' => 8,
        'name' => 'Burger Palace',
        'slug' => 'burger-palace',
        'address' => 'Piazza Venezia, 1, Roma',
        'phone' => '+39 308 791 2456',
        'vat' => '18987654321',
        'description' => 'Hamburger succulenti e patatine croccanti.',
        'image' => 'restaurants/burger-palace.png',
        'types' => ['Fast-Food'],
    ],
    [
        'user_id' => 9,
        'name' => 'Poke House',
        'slug' => 'poke-house',
        'address' => 'Via del Corso, 15, Roma',
        'phone' => '+39 309 384 7629',
        'vat' => '12345678901',
        'description' => 'Autentici piatti hawaiani freschi e gustosi.',
        'image' => 'restaurants/poke-house.jpg',
        'types' => ['Poke', 'Sushi', 'Vegetariano'],
    ],
    [
        'user_id' => 10,
        'name' => 'Nippon',
        'slug' => 'nippon',
        'address' => 'Piazza di Spagna, 2, Roma',
        'phone' => '+39 310 678 3951',
        'vat' => '22876543210',
        'description' => 'Sushi fresco e sashimi prelibati.',
        'image' => 'restaurants/nippon.jpeg',
        'types' => ['Giapponese', 'Sushi'],
    ],
    [
        'user_id' => 11,
        'name' => 'Ramen House',
        'slug' => 'ramen-house',
        'address' => 'Piazza Barberini, 9, Roma',
        'phone' => '+39 311 952 3876',
        'vat' => '23543210987',
        'description' => 'Ramen fumanti e gustosi brodi giapponesi.',
        'image' => 'restaurants/ramen-house.png',
        'types' => ['Giapponese', 'Vegetariano'],
    ],
    [
        'user_id' => 12,
        'name' => 'Sulemani Kebab',
        'slug' => 'sulemani-kebab',
        'address' => 'Via Appia, 20, Roma',
        'phone' => '+39 312 467 8912',
        'vat' => '24234567890',
        'description' => 'Kebab gustoso e pietanze mediorientali.',
        'image' => 'restaurants/suleman.jpg',
        'types' => ['Kebab'],
    ],
    [
        'user_id' => 13,
        'name' => 'BBQ Heaven',
        'slug' => 'bbq-heaven',
        'address' => 'Viale Trastevere, 30, Roma',
        'phone' => '+39 313 598 2746',
        'vat' => '25345678901',
        'description' => 'Grigliate succulente e carni alla brace.',
        'image' => 'restaurants/bbq-heaven.jpg',
        'types' => ['Barbecue'],
    ],
    [
        'user_id' => 14,
        'name' => 'Gelateria Delizia',
        'slug' => 'gelateria-delizia',
        'address' => 'Via Cola di Rienzo, 40, Roma',
        'phone' => '+39 314 782 6391',
        'vat' => '26456789012',
        'description' => 'Gelato artigianale e sorbetti freschi.',
        'image' => 'restaurants/gelateria-delizia.jpg',
        'types' => ['Italiano', 'Gelateria', 'Vegetariano'],
    ],
    [
        'user_id' => 15,
        'name' => 'Pasticceria Fantasia',
        'slug' => 'pasticceria-fantasia',
        'address' => 'Piazza Navona, 50, Roma',
        'phone' => '+39 315 391 2847',
        'vat' => '27567890123',
        'description' => 'Dolci deliziosi e pasticceria di alta qualità.',
        'image' => 'restaurants/pasticceria-fantasia.png',
        'types' => ['Pasticceria'],
    ],
    [
        'user_id' => 16,
        'name' => 'Caffè Italia',
        'slug' => 'caffe-italia',
        'address' => 'Via Veneto, 60, Roma',
        'phone' => '+39 316 874 5693',
        'vat' => '28678901234',
        'description' => 'Caffè pregiato e deliziosi dolci fatti in casa.',
        'image' => 'restaurants/caffetteria-italia.png',
        'types' => ['Italiano', 'Caffetteria'],
    ],
];
